version: '3.8'

services:
  pass-in-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pass_in_pg_data
    volumes:
      - pass_in_pg_data:/bitnami/postgresql


volumes:
  pass_in_pg_data: